In [2]:
#import
import numpy as np 

In [ ]:
# How vectors can be represented
x = [1,2,3]
y = [4,5,6]

z = []
for i in range(len(

In [3]:
#Vectors as List
x = [1,2,3]
print(x)

[1, 2, 3]


In [6]:
#Vectors as numpy array
x= np.array([1,2,3])
print(x,type(x))

[1 2 3] <class 'numpy.ndarray'>


In [10]:
X = np.arange(1,6)
X

array([1, 2, 3, 4, 5])

In [13]:
#advantage of nparray
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

In [16]:
## Important operations on vectors

# Element wise multiplication or Hadamard Product
x = np.arange(1,4)
y = np.arange(4,7)
z = x*y
z

array([ 4, 10, 18])

In [17]:
#scale vector
a = 3 * x
a

array([3, 6, 9])

In [26]:
#comparing python list with the numpy array
x = list(range(1,100000))
x_numpy = np.arange(1,100000)

In [28]:
comp = %timeit [2 * i for i in x]

11.3 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%timeit 2 * x_numpy

157 μs ± 10.5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
# Element wise function of vectors
# y = x**2
y = np.arange(1,5) ** 2
y

array([ 1,  4,  9, 16])

In [34]:
# y log(x)
val = np.log10(np.array([1,10,100,1000,10000]))
val

array([0., 1., 2., 3., 4.])

In [36]:
# Adding Scalar
x = np.array([1,2,3])
z = x + 2
z

array([3, 4, 5])

In [37]:
# f(x) = 5x - 2
x = np.array([-1,-2,-3,-4])
z = 5 * x - 2
z

array([ -7, -12, -17, -22])

In [38]:
# Dot product
# z = x*T.y
x= np.arange(1,5)
y = np.arange(-4,-8,-1)
x@y
  

np.int64(-60)

In [40]:
z = np.dot(x,y)
z

np.int64(-60)

In [41]:
# zeros vector
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [43]:
#ones vector
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [44]:
# vecotor with all element are 5
x = np.ones(5) * 5
x

array([5., 5., 5., 5., 5.])

In [48]:
x = np.array([1,2,3])
# l2 norm 
l2 = np.linalg.norm(x)
print("l2",l2)
l1 = np.linalg.norm(x,ord=1)
print("l1",l1)

l2 3.7416573867739413
l1 6.0


In [49]:
# shape -: No of components in vector
# dim :- No. of rows reqire to print the vector 1d,2d,3d
x = np.array([1,2,3,4])
shp = np.shape(x)
dim = np.ndim(x)
print(shp)
print(dim)

(4,)
1
